# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 19:44
from __future__ import unicode_literals

import crawler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('port', models.IntegerField(default=0)),
                ('proxy_types', models.IntegerField(choices=[(1, 'HTTP'), (2, 'HTTPS'), (4, 'SOCKS4'), (8, 'SOCKS5')], default=1)),
                ('last_checked_time', models.DateTimeField(auto_now=True)),
                ('last_checked_success', models.BooleanField(default=False)),
                ('last_checked_delay_ms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('script', models.CharField(max_length=2048, validators=[crawler.models.validate_python_script])),
                ('last_fetch_time', models.DateTimeField(auto_now=True)),
                ('last_fetch_success', models.BooleanField(default=False)),
                ('last_fetch_resources_found', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='sources',
            field=models.ManyToManyField(to='crawler.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together=set([('ip', 'port')]),
        ),
    ]
